name: Release and Publish to npm

on:
  push:
    branches: [ chore/setup-release-workflow ]

jobs:
  release:
    name: Test, Build, and Publish
    runs-on: ubuntu-latest

    permissions:
      contents: write # to push version commit and tag

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed for versioning

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Clone Thoth ID environment repository
        run: git clone --branch thoth-master https://github.com/Thoth-Namesystem/thoth-id.git thoth-id-env

      - name: Start Docker environment
        run: |
          cd thoth-id-env
          docker compose up -d

      - name: Wait for services to be ready
        run: sleep 30

      - name: Run test setup with retries
        run: |
          for i in 1 2 3; do
            if npm run test:setup; then
              echo "Test setup succeeded on attempt $i."
              exit 0
            fi
            if [ $i -lt 3 ]; then
              echo "Test setup failed on attempt $i. Retrying in 30 seconds..."
              sleep 30
            else
              echo "Test setup failed after 3 attempts."
              exit 1
            fi
          done

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build

      - name: Determine version bump from commit message
        id: version_bump
        run: |
          commit_message=$(git log -1 --pretty=%B)
          if [[ "$commit_message" == *"[major]"* || "$commit_message" == *"[breaking change]"* ]]; then
            echo "bump=major" >> $GITHUB_OUTPUT
          elif [[ "$commit_message" == *"[minor]"* || "$commit_message" == *"[feat]"* ]]; then
            echo "bump=minor" >> $GITHUB_OUTPUT
          else
            echo "bump=patch" >> $GITHUB_OUTPUT
          fi

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Bump version and create tag
        id: bump_version
        run: |
          new_version=$(npm version ${{ steps.version_bump.outputs.bump }} --no-git-tag-version)
          echo "new_version=$new_version" >> $GITHUB_OUTPUT
          git add package.json package-lock.json
          git commit -m "chore(release): ${new_version}"
          git tag ${new_version}

      - name: Push changes back to branch
        run: git push && git push --tags

      - name: Publish to npm
        if: false # Disabled for testing
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}